### ISSUE TITLE
net.sf.orcc.cal.cal.<type> cannot be resolved to a type.

### ISSUE THREAD

**Issue by kazuna69** [orcc/orcc#137]
just wondering what's the cause of this issue,
![image](https://cloud.githubusercontent.com/assets/15995513/11384425/9e881946-934a-11e5-9b70-7b9179246fa4.png)

I found the documentation here:
http://orcc.sourceforge.net/javadoc/net/sf/orcc/cal/cal/package-summary.html

but I couldn't find the package (to download), would it be possible to advise me on this issue?

**Comment by alorence** [comment]
Did you follow the steps described here: http://orcc.sourceforge.net/get-involved/contribution/ ?

Specifically, the missing packages are generated when you rune the MWE2 workflow:

    In the net.sf.orcc.cal project, under src/net/sf/orcc/cal, right-click on the GenerateCal.mwe2 file, and Run As MWE2 Workflow.

**Comment by eugeneu** [comment]
Hello @kazuna69! You can also try this very nice tutorial https://github.com/orcc/rvccaltut to get started.

**Comment by kazuna69** [comment]
thanks!
will try it again,
I did try follow every steps, seems not yet successful,
=/

**Comment by casalebrunet** [comment]
as @alorence mentioned before you should run the MWE2 workflow:

* go in the "net.sf.orcc.cal" project then src/net.sf.orcc/cal 
* select GenerateCal.mwe2
* right click -> Run As -> MWE2 Workflow

That's it =)
![screenshot from 2015-11-26 09 17 06](https://cloud.githubusercontent.com/assets/2758632/11418314/072771ac-941f-11e5-835f-75fb8f46c8fb.png)

**Comment by kazuna69** [comment]
I did, and I hit this error
http://pastebin.com/b7BHPz8g

I think I need help/advice on this, seems it prompt the "Value '2.11' is not legal" upon run as 'MWE2 workflow'
=/

**Comment by casalebrunet** [comment]
This issue is quite old, now we are using maven and we have not received any other related issue. I close this one
