### ISSUE TITLE
[C Backend] Fan-out buffer size

### ISSUE THREAD

**Issue by gustavcedersjo** [orcc/orcc#142]
The C backend cannot handle fan-out connections with different buffer sizes. It produces code where the readers assume different sizes, which results in wrong data when running the program. If it is not implemented, it should at least report an error.

**Comment by robstewart57** [comment]
Hi @gustavcedersjo ,

What exactly do you mean by fan-out connections? Are you referring to the case when one output port has two connections connected to that output port, feeding data to the input ports of 2 separate actors?

With respect to erroneous C code generation, the smallest possible reproducible example would be very helpful. That is, the smallest possible CAL Orcc project, pointing to the lines of generated C code that is wrong, and what you think the correct C should be?

**Comment by gustavcedersjo** [comment]
Yes, that's what I am referring to: One output port with two connections, and the connections having different buffer sizes.

(Actually, I have only tried having one connection with a specified size and the other with the default size.)

The generated C code creates a common buffer for the two connections, which is generally fine, but in this case the two consumer actors assumes different sizes of this buffer, making one of them read the wrong tokens.

There are several possible solutions to this problem, for example:
* Produce an error message
* Compute the buffer indices differently, accounting for (conceptually) different sizes.
* Create two buffers

**Comment by junaidjameel** [comment]
Hi @gustavcedersjo 

Thanks for reporting this. 

I think the most easiest fix is to produce an error message. Not sure how this is handled in other backends. But I will have a look and fix in C backend soon. 

Best,
Junaid

**Comment by junaidjameel** [comment]
Hi @gustavcedersjo 

We have fixed the issue by using the maximum buffer size of fan-out connections. 

Best,
Junaid
