### ISSUE TITLE
[SOLVED] No Actor displayed in Set/Update Refinement dialog in Eclipse 4.3

### ISSUE THREAD

**Issue by Bazmundi** [orcc/orcc#146]
[SOLUTION] add packages under src directory and not straight under project folder
======================================================

So gave up on install in Eclipse 4.7.   Downloaded Eclipse 4.3 Java environment and reinstalled orrc (see https://github.com/orcc/orcc/issues/144 and https://github.com/orcc/orcc/issues/145).

Followed hello world yet again.  Got different tool palette???

Under E4.3 the "Set/Update Environment" menu item works sort of.

Selection gets a dialogue (in E4.7 no dialogue was created).  Otherwise nothing is listed.

I have tried typing in hello, Hello HELLO, org. etc.  What you see below is the eclipse windows over the orcc tutorial for Hello World.  Eclipse windows shrunken and in bottom right.

What you don't see is the error message:

**Invalid refinement of vertex 'HelloInstance': 'null'	TopHelloOrcc.xdf	/HelloOrcc/org/tutorial/hellorcc	Unknown	Problem**

The error message appears if you drop the instance on the canvas and then hit save.

Unlike the E4.7 install, the code otherwise gets past checks without error reports.

So fresh install of Eclipse 4.3 JDT, fresh install of http://orcc.sourceforge.net/eclipse, create orcc project hello world as per help files.  

![cal](https://user-images.githubusercontent.com/1772587/38122175-0613b052-341b-11e8-85eb-ab2f6075b4b2.png)

**Comment by robstewart57** [comment]
@Bazmundi hi, can this issue be closed now?
